[necklace]
	# Default: 0.20000000298023224
	# Range: 0.0 ~ 1.0
	swim_sped = 0.20000000298023224
	# Default: 0.10000000149011612
	# Range: 0.0 ~ 1.0
	drowned_range_debuff = 0.10000000149011612
	# Default: 0.10000000149011612
	# Range: 0.0 ~ 1.0
	guardian_range_debuff = 0.10000000149011612

[grappling_hook]
	# Default: 1.0
	# Range: 0.0 ~ 10.0
	launch_speed = 1.0
	# Default: 4.0
	# Range: 1.0 ~ 1000.0
	max_speed = 4.0
	# Default: 32.0
	# Range: 4.0 ~ 128.0
	max_distance = 32.0

	[spawn_rates.leaf_insect]
		# Default: 14
		# Range: 0 ~ 128
		weight = 14
		# Default: 1
		# Range: 1 ~ 128
		min = 1
		# Default: 1
		# Range: 1 ~ 128
		max = 1

	[spawn_rates.red_panda]
		# Default: 8
		# Range: 0 ~ 128
		weight = 8
		# Default: 1
		# Range: 1 ~ 128
		min = 1
		# Default: 2
		# Range: 1 ~ 128
		max = 2

	[spawn_rates.jumping_spider]
		# Default: 2
		# Range: 0 ~ 128
		weight = 2
		# Default: 1
		# Range: 1 ~ 128
		min = 1
		# Default: 1
		# Range: 1 ~ 128
		max = 1

	[spawn_rates.ferret]
		# Default: 4
		# Range: 0 ~ 128
		weight = 4
		# Default: 2
		# Range: 1 ~ 128
		min = 2
		# Default: 3
		# Range: 1 ~ 128
		max = 3

	[spawn_rates.sea_bunny]
		# Default: 16
		# Range: 0 ~ 128
		weight = 16
		# Default: 1
		# Range: 1 ~ 128
		min = 1
		# Default: 4
		# Range: 1 ~ 128
		max = 4

	[spawn_rates.dumbo_octopus]
		# Default: 6
		# Range: 0 ~ 128
		weight = 6
		# Default: 1
		# Range: 1 ~ 128
		min = 1
		# Default: 1
		# Range: 1 ~ 128
		max = 1

	[spawn_rates.otter]
		# Default: 1
		# Range: 0 ~ 128
		weight = 1
		# Default: 3
		# Range: 1 ~ 128
		min = 3
		# Default: 5
		# Range: 1 ~ 128
		max = 5

	[spawn_rates.koi_fish]
		# Default: 4
		# Range: 0 ~ 128
		weight = 4
		# Default: 2
		# Range: 1 ~ 128
		min = 2
		# Default: 5
		# Range: 1 ~ 128
		max = 5

	[spawn_rates.dragonfly]
		# Default: 7
		# Range: 0 ~ 128
		weight = 7
		# Default: 1
		# Range: 1 ~ 128
		min = 1
		# Default: 1
		# Range: 1 ~ 128
		max = 1

	[spawn_rates.shima_enaga]
		# Default: 3
		# Range: 0 ~ 128
		weight = 3
		# Default: 2
		# Range: 1 ~ 128
		min = 2
		# Default: 3
		# Range: 1 ~ 128
		max = 3
